### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by simplcup** [dmlguq456/SepReformer#12]
m C:\Margio\SepReformer-main\models\SepReformer_Base_WSJ0\log\scratch_weights\epoch.0180.pth .....
Traceback (most recent call last):
  File "C:\Margio\SepReformer-main\run.py", line 32, in <module>
    main_module.main(args)
  File "C:\Margio\SepReformer-main\utils\decorators.py", line 12, in wrapped
    result = func(*args, **kwargs)
  File "C:\Margio\SepReformer-main\models\SepReformer_Base_WSJ0\main.py", line 43, in main
    engine = Engine(args, config, model, dataloaders, criterions, optimizers, schedulers, gpuid, device)
  File "C:\Margio\SepReformer-main\utils\decorators.py", line 12, in wrapped
    result = func(*args, **kwargs)
  File "C:\Margio\SepReformer-main\models\SepReformer_Base_WSJ0\engine.py", line 36, in __init__
    self.start_epoch = util_engine.load_last_checkpoint_n_get_epoch(self.checkpoint_path, self.model, self.main_optimizer, location=self.device)
  File "C:\Margio\SepReformer-main\utils\util_engine.py", line 42, in load_last_checkpoint_n_get_epoch
    checkpoint_dict = torch.load(latest_checkpoint_file, map_location=location)
  File "C:\Users\atom4\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1384, in load
    return _legacy_load(
  File "C:\Users\atom4\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

i get this error when trying to use the model, can someone please help me?

**Comment by john-zhaofei** [comment]
Maybe the pre-trained model was not downloaded correctly.

**Comment by jamesandrewclarke** [comment]
The model weights are handled using [Git LFS](https://git-lfs.com/), so make sure this is set up correctly.

Perhaps this should be mentioned in the documentation? I also ran into this problem and it wasn't immediately obvious.

**Comment by dmlguq456** [comment]
Thank you for your advice! I will correct it.

**Comment by sappho192** [comment]
@dmlguq456 Hi, if it's ok to you, I recommend you to upload model weights to Huggingface.
Git LFS served in Github consumes the monthly storage/bandwidth limit of your account (it's 1GB in free/pro plan) and it can be exhausted easily. (Check https://github.com/settings/billing/summary )
In contrast, you can upload any models Huggingface and doesn't bother you with the storage/bandwidth limit.

**Comment by PhilipAmadasun** [comment]
@dmlguq456  I initialized git LFS and still have the same error.  What do I do? ALso can you guys in the tutorial create a simple code to use the pretrained model in python code to extract speech and put the different speeches in seperate .wav files?

**Comment by jamesandrewclarke** [comment]
@PhilipAmadasun Ideally LFS is installed before cloning the repository. But you can also pull it down after cloning with `git lfs fetch`.

**Comment by simonmb** [comment]
I am running `git lfs fetch`, but I am getting the following error:

fetch: Fetching reference refs/heads/main
batch response: This repository exceeded its LFS budget. The account responsible for the budget should increase it to restore access.
error: failed to fetch some objects from 'https://github.com/dmlguq456/SepReformer.git/info/lfs'

would it be possible to host the files elsewhere? It seems there is significant interest. :)
